---
- hosts: localhost
  connection: local
  roles:
  - role: 'grycap.nfs'
    nfs_mode: 'front'
    nfs_exports:
    - {path: "/pv", export: "*.localdomain(rw,async,no_root_squash,no_subtree_check,insecure)"}

  - role: 'grycap.kubefaas'
    faas_framework: 'openfaas'
    functions_namespace: 'oscar-svc'
    master_deploy: true

  - role: 'grycap.kubeminio'
    minio_secretkey: '{{ oscar_minio_secretkey }}'
    master_deploy: true
    enable_tls: true

  - role: 'grycap.kuberegistry'
    public_access: false
    type_of_node: "front"
    delete_enabled: true
    master_deploy: true

  - role: 'grycap.kubeoscar'
    oscar_pass: '{{ oscar_password }}'
    create_ingress: true
    serverless_backend: 'openfaas'
    minio_endpoint:  'https://{{ IM_NODE_PUBLIC_IP }}:30300'
    minio_secret_key: '{{ oscar_minio_secretkey }}'
    minio_tls_verify: false
    master_deploy: true
