---
- hosts: localhost
  connection: local
  roles:
  - role: 'grycap.nfs'
    nfs_mode: 'front'
    nfs_exports:
    - {path: "/pv", export: "*.localdomain(rw,async,no_root_squash,no_subtree_check,insecure)"}

  - role: 'grycap.kubefaas'
    faas_framework: 'openfaas'
    master_deploy: true
    faas_chart_version: 5.4.0
    cli_version: 0.11.3
    oscar_worker_version: 1.2.1

  - role: 'grycap.kubeminio'
    enable_notifications: true
    webhook_endpoints: [{ id: "1", endpoint: "http://oscar-manager.oscar:8080/events"}]
    minio_secretkey: '{{ oscar_minio_secretkey }}'
    master_deploy: true
    enable_tls: false

  - role: 'grycap.kuberegistry'
    public_access: false
    type_of_node: "front"
    delete_enabled: true
    master_deploy: true

  - role: 'grycap.kubeoscar'
    minio_pass: '{{ oscar_minio_secretkey }}'
    vue_app_backend_host: '{{ hostvars[groups["front"][0]]["IM_NODE_PUBLIC_IP"] }}'
    master_deploy: true
    oscar_version: 1.2.0
    oscar_ui_version: 1.0.1
    supervisor_version: 1.1.2
    onetrigger_version: 1.0.4
