---
- hosts: localhost
  connection: local
  roles:
  - role: grycap.consul

  - role: grycap.nomad
    name: server 
    bind_address: "{{ IM_NODE_PRIVATE_IP }}"
    server_enabled: true
    client_enabled: false
    use_consul: true
    consul_address: "localhost:8500"
    create_nomad_service: true
