# adapted from https://github.com/DigitalPebble/ansible-storm
---
- hosts: storm_wn
  vars:
    # get IP of master from hostvars
    master_ip: "{{ storm_front_end_ip }}"

  tasks:
   - debug: var=master_ip

   - apt:
      name: openjdk-8-jdk
      state: present
     when: ansible_os_family == "Debian"

   - yum:
      name: java-1.8.0-openjdk
      state: present
     when: ansible_os_family == "RedHat"

   - group: name=storm system=yes state=present

   - name: Create Storm User
     user: name=storm system=yes createhome=false group=storm

   - name: Download Apache Storm {{ storm_version }}
     get_url:
       url: "https://www.mirrorservice.org/sites/ftp.apache.org/storm/apache-storm-{{ storm_version }}/apache-storm-{{ storm_version }}.tar.gz"
       dest: /tmp/
       owner: storm
       group: storm
       timeout: 600

   - name: Extract Apache Storm
     unarchive:
       src: /tmp/apache-storm-{{ storm_version }}.tar.gz
       dest: /usr/share/
       owner: storm
       group: storm
       remote_src: yes

   - file:
       path: "/usr/share/apache-storm-{{ storm_version }}"
       owner: "storm"
       group: "storm"
       mode: "u=rwx,g=rwx,o=r"
       recurse: yes
       state: directory

   - file:
       src: "/usr/share/apache-storm-{{ storm_version }}/bin/storm"
       dest: /usr/bin/storm
       owner: storm
       group: storm
       state: link

   - file:
       path: /var/log/storm
       owner: storm
       group: storm
       state: directory
       mode: "u=rwx,g=rwx,o=r"
       recurse: yes

   - file:
       path: /var/log/storm/workers-artifacts/
       owner: storm
       group: storm
       state: directory
       mode: "u=rwx,g=rwx,o=rwx"
       recurse: yes

   - name: Add master in hosts
     lineinfile:
       dest: /etc/hosts
       line: "{{master_ip}}  nimbus"

   - copy:
      dest: "/usr/share/apache-storm-{{ storm_version }}/conf/storm.yaml"
      content: |
        nimbus.host: "{{ front_end_ip }}"
        storm.log.dir: "/var/log/storm"
        storm.zookeeper.servers:
          - "{{ front_end_ip }}"
        nimbus.seeds: ["{{ front_end_ip }}"]
        storm.local.hostname: "{{ dns_name }}"
        worker.heap.memory.mb: 5000

   - copy:
      dest: "/etc/systemd/system/storm-{{ item }}.service"
      content: |
        [Unit]
        Description={{item}} service
        [Service]
        Type=simple
        ExecStart=/usr/bin/storm {{item}}
        Restart=always
        PIDFile=/var/run/%i.pid
        User=storm
        WorkingDirectory=/usr/share/apache-storm-{{ storm_version }}
        [Install]
        WantedBy=multi-user.target
     with_items:
        - supervisor
        - logviewer

   - lineinfile:
      state: present
      dest: /etc/default/grub
      backrefs: yes
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.* audit)\"[^\"]+)(\".*)'
      line: '\1 ipv6.disable=1\2'

   - name: grub disable ipv6
     shell: update-grub

   - name: sysctl disable ipv6
     shell: sysctl -w net.ipv6.conf.all.disable_ipv6=1

   - name: sysctl disable ipv6
     shell: sysctl -w net.ipv6.conf.default.disable_ipv6=1

   - systemd: state=started name=storm-{{ item }}.service daemon_reload=yes
     with_items:
        - supervisor
        - logviewer
