---
- hosts: localhost
  connection: local
  tasks:
    ###################################
    #  --- Users's Accounts --------  #
    ###################################

    - set_fact:
        accounts: "{{ accounts | default([]) + [{'name': item, 'pw': lookup('password', '/var/tmp/passwordfile_' + item + ' length=8')}] }}"
      with_sequence: start=0 end={{ user_num }} format=user%02x

    - name: Create user accounts
      user: name={{ item.name }} password={{ item.pw }} shell=/bin/bash generate_ssh_key=yes
      with_items: "{{ accounts }}"

    - name: Create $HOME/.ssh directory
      file: path=/home/{{ item.name }}/.ssh state=directory owner={{ item.name }} group={{ item.name }} mode=0700
      with_items: "{{ accounts }}"

    - name: Modify $HOME permissions
      file: path=/home/{{ item.name }} state=directory owner={{ item.name }} group={{ item.name }} mode=0700
      with_items: "{{ accounts }}"



