---
- hosts: localhost
  connection: local
  vars:
    IM_SERVER: "https://appsgrycap.i3m.upv.es:31443/im"

  tasks:
  - name: Install IM Client
    pip:
      name: im-client

  - name: Export infra
    get_url:
      url: "{{IM_SERVER}}/infrastructures/{{ IM_INFRASTRUCTURE_ID }}/data"
      dest: /usr/local/ec3/inf.json

  - name: Inport infra
    shell: im_client.py -a /usr/local/ec3/auth.dat import /usr/local/ec3/inf.json && touch /usr/local/ec3/imported
    args:
      creates: /usr/local/ec3/imported

  - name: Delete infra
    get_url:
      url: "{{IM_SERVER}}/infrastructures/{{ IM_INFRASTRUCTURE_ID }}/data?delete=yes"
      dest: /usr/local/ec3/inf2.json

