---
- hosts: localhost
  connection: local
  roles:
  - role: grycap.docker

  tasks:
  - name: Install Git
    package: name=git

  - name: Git Dowload
    git:
      repo: https://gitlab.com/openbiomaps/docker/obm-composer.git
      dest: /opt/openbiomaps
      version: master
      update: no

  - name: Create obm_web network
    docker_network:
      name: obm_web

  - name: OBM pre install
    command: ./obm_pre_install.sh
    args:
      chdir: /opt/openbiomaps

  - name: OBM compose up
    command: docker-compose up -d
    args:
      chdir: /opt/openbiomaps

  - name: OBM post install
    shell: ./obm_post_install.sh && touch /opt/openbiomaps/post
    args:
      chdir: /opt/openbiomaps
      creates: /opt/openbiomaps/post