---
- hosts: localhost
  connection: local
  roles:
  - role: grycap.docker

  tasks:
  - name: Install Git
    package: name=git

  - name: Git Dowload
    git:
      repo: https://gitlab.com/openbiomaps/docker/obm-composer.git
      dest: /opt/openbiomaps
      version: devel

  - name: Create obm_web network
    docker_network:
      name: obm_web

  - name: OBM compose up
    command: docker-compose -up -d chdir=/opt/openbiomaps