---
- hosts: localhost
  connection: local
  vars:
    IM_SERVER: "https://appsgrycap.i3m.upv.es:31443/im"

  tasks:
  # Reconfigure clues to use IM_SERVER
  - name: Set IM plugin configuration file values
    ini_file: dest=/etc/clues2/conf.d/plugin-im.cfg section="IM VIRTUAL CLUSTER" option={{ item.option }} value="{{ item.value }}"
    with_items:
      - { option: 'IM_VIRTUAL_CLUSTER_REST_API', value: "{{ IM_SERVER }}" }
    notify: restart cluesd
